development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "gary525t@gmail.com" 
  password: "Yiso_525"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "gary525t@gmail.com" 
  password: "Yiso_525"
  enable_starttls_auto: true

