development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "yiso05255@gmail.com" 
  password: "Gary_525"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "yiso05255@gmail.com" 
  password: "Gary_525"
  enable_starttls_auto: true

